### ISSUE TITLE
[Bug] Can't add new image to new node

### ISSUE THREAD

**Issue by ferreirajoaouerj** [nnako/freeplane-python-io#2]
Hello! Nice library!

I believe there is a bug when adding an image to a new node. 

`mm = freeplane.Mindmap('test.mm')`
`node = mindmap.rootnode.add_child('test')`
`node.set_image("img.png")`
`mindmap.save('test.mm')`

When you open the `test.mm` mind map you will notice there is no image and an error message appears. I believe this can be fixed on line 1335:

`SIZE=str(link),`

I think it should be:

`SIZE=str(size)`

You could create a new branch for bug fixing and maybe other people can suggest fixes!

**Comment by nnako** [comment]
Hi @ferreirajoaouerj . Thanks for your bug report. The issue is solved in commit https://github.com/nnako/freeplane-python-io/commit/fd0c18e3572b5c7818812e50c7426e6955221093 . I would appreciate you checking if the issue is solved. Therefore you would have to locally update the `source code` as these changes are not uploaded to PyPi, yet.

Thanks.

**Comment by nnako** [comment]
just created **v0.8.0** on PyPi.

you should easily be able to update using `pip`.
